### ISSUE TITLE
About NTU_ Problems with similarity.py

### ISSUE THREAD

**Issue by feiniao66** [chico2121/bpe#10]
![image](https://user-images.githubusercontent.com/94954658/143577997-f8970bf9-dfe3-4c23-9d32-b19deb688ad2.png)
Here -- Model_ Path means to put all. PTH files in the model folder, or just one of them?

**Comment by BAILOOL** [comment]
It is the path to all models produced during the training stage. During training the model is saved every epoch. So this script evaluates all those saved models to simply select the best one.

**Comment by feiniao66** [comment]
ok, thank you
