### ISSUE TITLE
Question about function parameters

### ISSUE THREAD

**Issue by ghost** [chico2121/bpe#13]
Could you better explain the video_sampling_window_size and video_sampling_stride parameters? If I want to run a query motion through a longer video, is that what those parameters will do? Apply dtw like a sliding window and search similarities?

**Comment by BAILOOL** [comment]
Hi @MagnusAnders. Thank you for the interest in this work. Indeed, those parameters are used to split video sequences into patches. More information can be found in the Sec III, B "MEASURING MOTION SIMILARITY" of the paper:
<img width="567" alt="image" src="https://user-images.githubusercontent.com/11172777/159506986-27bbb0a8-fbff-44a5-9f8c-79d8235998c1.png">

**Comment by ghost** [comment]
And what is the output of the code? Just the most similar motion? Or is there also a parameter to define how many motions to return?

**Comment by ghost** [comment]
And sorry, I guess the output should be an array with the score for each body embedding and the timestamps. Is that right?

**Comment by BAILOOL** [comment]
What script/code do you refer to @MagnusAnders ?

**Comment by ghost** [comment]
Inference_single_pair_visuals.py 
Here, there is the option for the sliding window approach.

**Comment by ghost** [comment]
I was asking what is the output of this code ? Sorry for the misunderstanding

**Comment by BAILOOL** [comment]
It should produce a video (see https://github.com/chico2121/bpe/blob/f05e273bca542f1f1e0bfcb97bfce59b1f837e37/bin/inference_single_pair_visuals.py#L117) with input human keypoints and motion similarity score for every video patch that is determined by the parameters of the sliding window.

**Comment by ghost** [comment]
So, the last paragraph of the text you send in the first message is something we have to calculate. The output of the function doesn’t return it by itself right ?

**Comment by BAILOOL** [comment]
You can average the list of motion similarities for each patch `motion_similarity_per_window` to determine the final motion similarity score of two sequences.

**Comment by ghost** [comment]
Sorry Alex maybe I didn’t explained right… if we want to use the sliding window approach, for example we have an action of 2s and we want to search similarities in a 10 min video. There will be multiple similarity actions that the algorithm will have to compute right ? I was asking, what will be the output since it will need to make several calculation to compute similarities. If the output is a video, I don’t think it makes sense. So Why to use this approach ? Was I more clear now ?
Sorry for the confusion

**Comment by ghost** [comment]
> You can average the list of motion similarities for each patch `motion_similarity_per_window` to determine the final motion similarity score of two sequences.

Ok right

**Comment by BAILOOL** [comment]
> Sorry Alex maybe I didn’t explained right… if we want to use the sliding window approach, for example we have an action of 2s and we want to search similarities in a 10 min video. There will be multiple similarity actions that the algorithm will have to compute right ? I was asking, what will be the output since it will need to make several calculation to compute similarities. If the output is a video, I don’t think it makes sense. So Why to use this approach ? Was I more clear now ? Sorry for the confusion

This method is about producing motion similarity scores of humans in video patches, though it can be adapted for searching similar motions in different videos. This repository does not contain the latter functionality.

**Comment by ghost** [comment]
Ok got it! 
Thanks

**Comment by ghost** [comment]
Sorry, just one more question. How fast is this code extracting motion similarity per window? Is it possible to apply then for a lot of segments so it can check similarities in a long video?

**Comment by BAILOOL** [comment]
@MagnusAnders please see Sec V, D. APPLICATION: 

`To compare two video clips (3.5 minutes long, 24fps) the
proposed method took about 7.8s (approx. 670fps) on CPU
(Intel Xeon 5120 @ 2.20GHz) without model or code optimization. This included joints data preprocessing, network
inference, and motion similarity calculation while excluding
the pose estimation extraction.`

I would advise you to investigate the paper as most of the implementation details are covered quite extensively. Good luck!
