### ISSUE TITLE
 pretrained model 

### ISSUE THREAD

**Issue by RCpengnan** [chico2121/bpe#16]
Thanks for excellent work, I use GTX2060-6G to train,but program was killed.Could you provided any pretrained model?

**Comment by BAILOOL** [comment]
@RCpengnan thank you for the interest in this work. Please refer to https://github.com/chico2121/bpe/issues/5

**Comment by RCpengnan** [comment]
> @RCpengnan感谢您对这项工作的兴趣。请参考#5
Thank you very much!
