### ISSUE TITLE
One question about inference_single_pair_visuals

### ISSUE THREAD

**Issue by RCpengnan** [chico2121/bpe#17]
![image](https://user-images.githubusercontent.com/74439931/168754739-aed928b6-a954-493d-b013-6e98e002b981.png)
Could you tell me How to get meanpose.npy or stdpose.npy?Thank you !

**Comment by BAILOOL** [comment]
AFAIR, those files are created during the dataset loading, see https://github.com/chico2121/bpe/blob/f05e273bca542f1f1e0bfcb97bfce59b1f837e37/bpe/dataset/unity_base_dataset.py#L82

**Comment by RCpengnan** [comment]
> AFAIR, those files are created during the dataset loading, see
> 
> https://github.com/chico2121/bpe/blob/f05e273bca542f1f1e0bfcb97bfce59b1f837e37/bpe/dataset/unity_base_dataset.py#L82

Thanks for your reply!

**Comment by wtnan2003** [comment]
@BAILOOL @RCpengnan ，If I want to use inference_single_pair_visuals.py with a pretrained model, do I need to run train_bpy.py to generate meanpose.npy and stdpose.npy ? Any help would be appreciated.
