### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ygywdr** [chico2121/bpe#2]
The repo has been deleted. Could you update it?

**Comment by BAILOOL** [comment]
@ygywdr What repo are you referring to?

**Comment by ygywdr** [comment]
@BAILOOL git clone https://github.com/dade-ai/bpe-dev.git
A Body Part Embedding Model with Datasets for Measuring 2D Human Motion Similarity

**Comment by BAILOOL** [comment]
@ygywdr where did you find a link to that repo?

**Comment by BAILOOL** [comment]
I guess you are referring to the Installation instructions in the README. Thank you for pointing it out @ygywdr

**Comment by ygywdr** [comment]
@BAILOOL And the Code in repository is not up to date.

**Comment by BAILOOL** [comment]
@ygywdr could you please be more specific on what parts are not up to date?

**Comment by ygywdr** [comment]
In unity_base_dataset.py line 67, the self.character_names is wrong. I guess it is not latest. And I can't run it now.

**Comment by ygywdr** [comment]
@BAILOOL

**Comment by ygywdr** [comment]
In unity_base_dataset.py line 67, the self.character_names is wrong. I guess it is not the latest. And I can't run it now.

**Comment by BAILOOL** [comment]
I think it is better to create a separate issue for that and assign it to @chico2121. Let's keep this issue for the installation related bug. Sorry for the inconvenience @ygywdr
