### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by ygywdr** [chico2121/bpe#4]
In unity_base_dataset.py line 67, the self.character_names is wrong. I guess it is not the latest. And I can't run it now.

**Comment by chico2121** [comment]
My apologize for the inconvenience. The character names have been corrected to match the SARA dataset.

**Comment by ygywdr** [comment]
@chico2121 Line 95 in unity_base_dataset.py, 'glob_path' does not match the dataset. And I'm sure this is not the last discrepancy. Could you provide the dataset used for the experiment or the latest code?

**Comment by BAILOOL** [comment]
@ygywdr I also experienced the same problem when running the code. I am currently working on PR to fix the discrepancies.  Will be coming soon.
