### ISSUE TITLE
Thanks for excellent work, wanna ask any pretrained model provided?

### ISSUE THREAD

**Issue by hokiwood-geek** [chico2121/bpe#5]

**Comment by BAILOOL** [comment]
@hokiwood-geek I am planning on retraining from scratch. However, I am currently experiencing [the issue](https://github.com/chico2121/SARA_Dataset/issues/2) with the dataset extraction. I will upload my tensorboard logs and trained models once I solve that issue.

**Comment by BAILOOL** [comment]
@hokiwood-geek I have managed to train the network using the modifications in #7. This [log directory](https://drive.google.com/drive/folders/1Ar9Av4_8KgfRL28kjmdGJ84RkwIit7gp?usp=sharing) contains tensorboard file as well as all the models produced during the training.

**Comment by yuxiaohui78** [comment]
Is there a pre-trained model available?

**Comment by wtnan2003** [comment]
Is there a pre-trained model available?

**Comment by BAILOOL** [comment]
> Is there a pre-trained model available?

This log directory contains tensorboard file as well as all the models produced during the training. @wtnan2003
