### ISSUE TITLE
ERROR for try to run the train demo

### ISSUE THREAD

**Issue by BALDman66** [chico2121/bpe#8]
This error occurred when I added the dataset and tried to train because the dataset was too large??？
![image](https://user-images.githubusercontent.com/59443639/142857073-76025881-d692-45f8-9f58-403ad777de69.png)

**Comment by BAILOOL** [comment]
In order to optimise for training speed, the code loads all ground truth values to memory and reads from there. Hence, it is possible that data preprocessing stage runs out of memory on a machine with a relatively low RAM.

However, from the picture you've uploaded, it looks like preprocessing step breaks on the first iteration. This might mean that, perhaps, data processing wasn't done in a way described at https://github.com/chico2121/SARA_Dataset

**Comment by BALDman66** [comment]
Thank you for your answer. I did use the supplied SARA data set and preprocessed it using the preprocess.py method
![image](https://user-images.githubusercontent.com/59443639/143009554-fe1d34e9-99e0-49c4-9435-9bc76ee4dff8.png)
![image](https://user-images.githubusercontent.com/59443639/143010632-583d2c6d-8787-427c-a09c-fc9fc4b3f253.png)

**Comment by BAILOOL** [comment]
Could you please provide your execution environment configuration (python and PyTorch version) and a command line you use to run the script? I will try to run it on my side to see if the same error is observed.

**Comment by BALDman66** [comment]
Thank you very much for your patient reply！python3.7 and  pytorch 1.4.0  Here are the parameters I configured to run the train file
![image](https://user-images.githubusercontent.com/59443639/143157104-50e113d5-32f0-4683-a443-301967e4d2c7.png)
Please understand that I have so many questions，I added the weight file of training completion you provided yesterday and tried to run ntu_content.py, but it seems there is still a problem with SARA data set??
![image](https://user-images.githubusercontent.com/59443639/143158335-0f9dc115-8ff6-4dbf-b029-f901b5c62906.png)

**Comment by BAILOOL** [comment]
Yesterday, I tried to run the code with similar settings and it worked fine. Try to run training first at least for 1 iteration. As a part of training preprocessing those meanpose*.npy files are created. After that you will be able to run ntu_similiarity.py
