### ISSUE TITLE
I also had problems with SARA datasets

### ISSUE THREAD

**Issue by feiniao66** [chico2121/bpe#9]
![image](https://user-images.githubusercontent.com/94954658/143194986-88dbdd16-b437-4698-80a2-310c2b65d7f4.png)
The code circled in the red box in the figure sets the global path to find all. NPY files under the path, but I run the motion below_ CACHE_ PATH,MOTION_ CACHE_ PATH_ MOTION_ NAMES,MOTION_ CACHE_ PATH_ VARIATION_ NAMES,MOTION_ CACHE_ PATH_ VARIATION_ Names, the paths of these names are forced together, resulting in an error below.
![0 VC$OPV K11~J~7MBPKXT2](https://user-images.githubusercontent.com/94954658/143196383-9afb9b78-577e-46ba-81a9-d4b44391880a.png)

**Comment by BAILOOL** [comment]
What's the error exactly?

**Comment by feiniao66** [comment]
![image](https://user-images.githubusercontent.com/94954658/143199034-adeada10-7e3a-41ae-9799-30ab3ededfb9.png)
Whether there is an error in the operation from the upper red box to the lower red box in the figure. In this way, the data in fusefemalea is read only.
Thank you for your answer

**Comment by feiniao66** [comment]
![79Z%Q4 A_8S9YYX$FEZP1`6](https://user-images.githubusercontent.com/94954658/143202118-d50ad2d6-c4b9-496d-a572-a264fc7f84e5.png)
This is the problem situation。

**Comment by BAILOOL** [comment]
Everything works fine for me on Linux and MacOS. I think it is reasonable to verify how glob behaves on Windows, as in the mentioned path you have combination of unix and dos characters for folder separation.

**Comment by feiniao66** [comment]
I have also run on UNIX, and this problem will also occur. This code means to create three. Pickle files and train them in the root directory_ In cache。
![PITJP%)16XDGGA KLEIXYCS](https://user-images.githubusercontent.com/94954658/143205941-731f108c-24eb-4918-ae1a-91337f2d4e77.png)
Thank you for your reply.

**Comment by BAILOOL** [comment]
Yes, I can see the pickle files created. And after that the training starts without any errors. Is it not the case for you?

**Comment by feiniao66** [comment]
![image](https://user-images.githubusercontent.com/94954658/143222192-4926ec95-ae60-4209-b16c-ed87ecc48f38.png)
An error will be reported when running here.

**Comment by BAILOOL** [comment]
It does look like it is Windows problem. For those lines, could you please try to specify the path manually and see what happens.

**Comment by feiniao66** [comment]
OK, I've been trying to do this these days, but there are some problems. Here are the solutions:
First, I will glob_ The path is changed as shown in the figure below:
![CQM$1%0F82(~7`@0PT}5ZNQ](https://user-images.githubusercontent.com/94954658/143229740-3b348c94-b52a-416e-b607-3f37df518e44.png)

Secondly, I run this program and in training_ These files are found in the cache:
![ZG{Z7IM47A@VN0CINMPREY4](https://user-images.githubusercontent.com/94954658/143229761-b21e8fc2-601f-42fb-917e-77b4adb16eeb.png)

But in the end, the program failed:
![`A`IVT_VX`I_Q5$N_0TY`6H](https://user-images.githubusercontent.com/94954658/143229781-a20fb520-5f8b-422f-bccd-2a9b9ae7848b.png)

Thank you for your time

**Comment by BAILOOL** [comment]
That's interesting. I have verified everything works for me on Linux and MacOS. So the only explanation that I can come up with is the problem with glob or paths (mix or dos/unix paths) on Windows. I am not familiar with running python and PyTorch on Windows. Perhaps @chico2121 can be of help here.

**Comment by feiniao66** [comment]
I hope you can tell me about your environment, such as the Linux version, because I want to reproduce this according to your method, please.
I hope you can be as detailed as possible. It's been bothering me for a long time. Thank you very much.

**Comment by feiniao66** [comment]
Hello, I'd like to see your traininh_ The files in the cache folder, I think this may help me solve this difficulty. You can tell me by screenshot.
Thank you very much

**Comment by BAILOOL** [comment]
@feiniao66, the files in the cache folder I get when starting the training script:
![image](https://user-images.githubusercontent.com/11172777/143681197-9b130550-1be5-4084-9117-4373c4ff2076.png)

**Comment by feiniao66** [comment]
OK, seeing this directory, I think I have solved this problem. Indeed, many details are different in windows. For example, numwoke can only be zero.
Thank you very much for your reply

**Comment by sqh123123** [comment]
> 好的，看到这个目录，我想我已经解决了这个问题。确实，windows 中的很多细节都是不同的。例如，numwoke 只能默认。 非常感谢您的回复
May I ask if you have successfully completed this project? May I ask you any related questions，please，i need your help

**Comment by sqh123123** [comment]
> 好的，看到这个目录，我想我已经解决了这个问题。确实，windows中的很多细节都是不同的。例如，numwoke只能默认。 非常感谢您的回复

If you see my question, please contact me. I think we can discuss this project
